### ISSUE TITLE
포지션 결정

### ISSUE THREAD

**Issue by layer26** [10sa/SamSame#1]
각자 희망 하는 포지션 작성할 것.

# List of positions
 * Lead Developer (LD; CTO)
   * Backend - Frontend 간 개발 도움, 프로그램 전체 기술 관리.
 * Project Manager (PM)
   * 프로젝트 형상 관리.
 * Backend Developer
   * 서버 개발 및 API 구현.
 * Frontend Developer
   * 웹 페이지 구현, 서버 API 사용.
 * Designer
   * 웹 페이지 리소스 제작.

**Comment by layer26** [comment]
개발 팀장 (Lead Developer; LD)

**Comment by devminchan** [comment]
백앤드 개발자 or CTO

## Edit by Owner
 * Backend Developer
 * Lead Developer

**Comment by AtaraOvO** [comment]
디자인 담당

## Edit by Owner
 * Desinger

**Comment by EunJin0731** [comment]
Project Manager (PM)
프로젝트 형상 관리
Frontend Developer
웹 페이지 구현, 서버 API 사용

**Comment by GahyeonC** [comment]
Backend Developer

**Comment by layer26** [comment]
완료, 결정 후 PM이 결정된 포지션을 코멘트로 달아둘 것.

@EunJin0731
